version: "2"
linters:
  enable:
    - bodyclose
    - dogsled
    - gocritic
    - godox
    - misspell
    - nakedret
    - prealloc
    - staticcheck
    - unconvert
    - unparam
    - whitespace
  settings:
    gocritic:
      disabled-checks:
        - elseif
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
