linters:
  enable:
    - bodyclose
    - dogsled
    - gocritic
    - godox
    - gofmt
    - goimports
    - misspell
    - nakedret
    - prealloc
    - stylecheck
    - unconvert
    - unparam
    - whitespace
linters-settings:
  gocritic:
    disabled-checks:
      - elseif
