# yaml-language-server: $schema=https://goreleaser.com/static/schema.json

version: 2
project_name: gogh
release:
  target_commitish: '{{ .Env.GITHUB_SHA }}'
builds:
  - id: default
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    main: ./cmd/gogh
    binary: gogh
    ldflags: -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}
    hooks:
      post:
        - make man VERSION={{.Version}} COMMIT={{.ShortCommit}} DATE={{.Date}}
homebrew_casks:
  - name: gogh
    binaries:
      - gogh
    manpages:
      - gogh*.1
    repository:
      owner: kyoh86
      name: homebrew-tap
    directory: Casks
    url:
      verified: github.com/kyoh86/gogh
    homepage: https://github.com/kyoh86/gogh
    description: GO GitHub project manager
    license: MIT
nfpms:
  - ids:
      - default
    maintainer: kyoh86 <me@kyoh86.dev>
    homepage: https://github.com/kyoh86/gogh
    description: GO GitHub project manager
    license: MIT
    formats:
      - apk
      - deb
      - rpm
archives:
  - id: gzip
    formats: ['tar.gz']
    format_overrides:
      - goos: windows
        formats: ['zip']
    files:
      - licence*
      - LICENCE*
      - license*
      - LICENSE*
      - readme*
      - README*
      - changelog*
      - CHANGELOG*
