brews:
  - install: |
      bin.install "gogh"
      man1.install "gogh.1"
    tap:
      owner: kyoh86
      name: homebrew-tap
    folder: Formula
    homepage: https://github.com/kyoh86/gogh
    description: GO GitHub project manager
builds:
  - goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm
      - arm64
      - "386"
    hooks:
      pre: make man
archives:
  - id: gzip
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    files:
      - licence*
      - LICENCE*
      - license*
      - LICENSE*
      - readme*
      - README*
      - changelog*
      - CHANGELOG*
      - gogh.1
