// Code generated by interfacer; DO NOT EDIT

package command

import (
	"github.com/kyoh86/gogh/internal/git"
	"io"
	"net/url"
)

// GitClient is an interface generated for "github.com/kyoh86/gogh/internal/git.Client".
type GitClient interface {
	AddRemote(string, string, *url.URL) error
	Clone(string, *url.URL, bool) error
	Fetch(string) error
	GetCurrentBranch(string) (string, error)
	GetRemote(string, string) (*url.URL, error)
	GetRemotes(string) (map[string]*url.URL, error)
	GetStatusSummary(string, io.Writer) (git.StatusSummary, error)
	Init(string, bool, string, string, string) error
	RemoveRemote(string, string) error
	RenameRemote(string, string, string) error
	SetUpstreamTo(string, string) error
	Status(string, io.Writer, io.Writer) error
	Update(string) error
}
