// Code generated by interfacer; DO NOT EDIT

package command

import (
	"github.com/google/go-github/v29/github"
	"github.com/kyoh86/gogh/gogh"
	"net/url"
)

// HubClient is an interface generated for "github.com/kyoh86/gogh/internal/hub.Client".
type HubClient interface {
	Create(gogh.Env, *gogh.Repo, string, *url.URL, bool) (*github.Repository, error)
	Fork(gogh.Env, *gogh.Repo, string) (*gogh.Repo, error)
	Repos(gogh.Env, string, bool, bool, bool, string, string, string) ([]string, error)
}
