version: 2
jobs:
  build:
    working_directory: /go/src/github.com/kyoh86/gogh
    docker:
      - image: kyoh86/gotest
    steps:
      - checkout
      - run:
          name: go test
          command: "go test -race ./..."
      - persist_to_workspace:
          root: /go
          paths:
            - "src"
            - "pkg"
            - "bin"
  cover:
    working_directory: /go/src/github.com/kyoh86/gogh
    docker:
      - image: kyoh86/gotest
    steps:
      - attach_workspace:
          at: /go
      - run:
          name: take a coverage
          command: "go test -coverprofile=coverage.out ./..."
      - run:
          name: upload a coverage
          command: "bash <(curl -s https://codecov.io/bash)"
  lint:
    working_directory: /go/src/github.com/kyoh86/gogh
    docker:
      - image: kyoh86/gotest
    steps:
      - attach_workspace:
          at: /go
      - run:
          name: search lints
          command: "gometalinter --config /etc/gometalinter/config.json ./... | grep -vFe '../pkg/mod/' | tee >( reviewdog -f=golint -reporter=github-pr-check )"

workflows:
  version: 2
  commit:
    jobs:
      - build
      - cover:
          requires:
            - build
      - lint:
          requires:
            - build
