version: 2
jobs:
  build:
    working_directory: /go/src/github.com/kyoh86/gogh
    docker:
      - image: "kyoh86/gotest:latest-module"
    steps:
      - checkout
      - run:
          name: vendor
          command: "go mod vendor"
      - run:
          name: go build
          command: "go build ./..."
      - run:
          name: go test and take coverage
          command: "go test -race -coverprofile=coverage.out ./..."
      - run:
          name: upload a coverage
          command: "bash <(curl -s https://codecov.io/bash)"
      - persist_to_workspace:
          root: /go
          paths:
            - "src"
            - "pkg"
            - "bin"
  lint:
    working_directory: /go/src/github.com/kyoh86/gogh
    docker:
      - image: kyoh86/gotest:latest
    steps:
      - attach_workspace:
          at: /go
      - run:
          name: search lints
          command: "gometalinter --config /etc/gometalinter/config.json ./... | tee >( reviewdog -f=golint -reporter=github-pr-check )"

  release:
    working_directory: /go/src/github.com/kyoh86/gogh
    docker:
      image: kyoh86/gotest:latest-module
    steps:
      - attach_workspace:
          at: /go
      - run:
          name: goreleaser
          command: "goreleaser --rm-dist"

workflows:
  version: 2
  commit:
    jobs:
      - build
      - lint:
          requires:
            - build
      - release:
          requires:
            - lint
          branches:
            ignore: /.*/
          tags:
            only: /^v[0-9](\.[0-9]){2}$/
