// Code generated by MockGen. DO NOT EDIT.
// Source: ./workspace/overlay_service.go
//
// Generated by this command:
//
//	mockgen -source ./workspace/overlay_service.go -destination ./workspace_mock/gen_overlay_service_mock.go -package workspace_mock
//

// Package workspace_mock is a generated GoMock package.
package workspace_mock

import (
	context "context"
	io "io"
	iter "iter"
	reflect "reflect"

	repository "github.com/kyoh86/gogh/v4/core/repository"
	workspace "github.com/kyoh86/gogh/v4/core/workspace"
	gomock "go.uber.org/mock/gomock"
)

// MockOverlayStore is a mock of OverlayStore interface.
type MockOverlayStore struct {
	ctrl     *gomock.Controller
	recorder *MockOverlayStoreMockRecorder
	isgomock struct{}
}

// MockOverlayStoreMockRecorder is the mock recorder for MockOverlayStore.
type MockOverlayStoreMockRecorder struct {
	mock *MockOverlayStore
}

// NewMockOverlayStore creates a new mock instance.
func NewMockOverlayStore(ctrl *gomock.Controller) *MockOverlayStore {
	mock := &MockOverlayStore{ctrl: ctrl}
	mock.recorder = &MockOverlayStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOverlayStore) EXPECT() *MockOverlayStoreMockRecorder {
	return m.recorder
}

// AddOverlay mocks base method.
func (m *MockOverlayStore) AddOverlay(ctx context.Context, entry workspace.Overlay, content io.Reader) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddOverlay", ctx, entry, content)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddOverlay indicates an expected call of AddOverlay.
func (mr *MockOverlayStoreMockRecorder) AddOverlay(ctx, entry, content any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddOverlay", reflect.TypeOf((*MockOverlayStore)(nil).AddOverlay), ctx, entry, content)
}

// FindOverlaysForPattern mocks base method.
func (m *MockOverlayStore) FindOverlaysForPattern(ctx context.Context, pattern string) iter.Seq2[*workspace.Overlay, error] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindOverlaysForPattern", ctx, pattern)
	ret0, _ := ret[0].(iter.Seq2[*workspace.Overlay, error])
	return ret0
}

// FindOverlaysForPattern indicates an expected call of FindOverlaysForPattern.
func (mr *MockOverlayStoreMockRecorder) FindOverlaysForPattern(ctx, pattern any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindOverlaysForPattern", reflect.TypeOf((*MockOverlayStore)(nil).FindOverlaysForPattern), ctx, pattern)
}

// FindOverlaysForReference mocks base method.
func (m *MockOverlayStore) FindOverlaysForReference(ctx context.Context, ref repository.Reference) iter.Seq2[*workspace.Overlay, error] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindOverlaysForReference", ctx, ref)
	ret0, _ := ret[0].(iter.Seq2[*workspace.Overlay, error])
	return ret0
}

// FindOverlaysForReference indicates an expected call of FindOverlaysForReference.
func (mr *MockOverlayStoreMockRecorder) FindOverlaysForReference(ctx, ref any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindOverlaysForReference", reflect.TypeOf((*MockOverlayStore)(nil).FindOverlaysForReference), ctx, ref)
}

// ListOverlays mocks base method.
func (m *MockOverlayStore) ListOverlays(ctx context.Context) ([]workspace.Overlay, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListOverlays", ctx)
	ret0, _ := ret[0].([]workspace.Overlay)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListOverlays indicates an expected call of ListOverlays.
func (mr *MockOverlayStoreMockRecorder) ListOverlays(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListOverlays", reflect.TypeOf((*MockOverlayStore)(nil).ListOverlays), ctx)
}

// OpenOverlay mocks base method.
func (m *MockOverlayStore) OpenOverlay(ctx context.Context, entry workspace.Overlay) (io.ReadCloser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OpenOverlay", ctx, entry)
	ret0, _ := ret[0].(io.ReadCloser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// OpenOverlay indicates an expected call of OpenOverlay.
func (mr *MockOverlayStoreMockRecorder) OpenOverlay(ctx, entry any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OpenOverlay", reflect.TypeOf((*MockOverlayStore)(nil).OpenOverlay), ctx, entry)
}

// RemoveOverlay mocks base method.
func (m *MockOverlayStore) RemoveOverlay(ctx context.Context, entry workspace.Overlay) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveOverlay", ctx, entry)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveOverlay indicates an expected call of RemoveOverlay.
func (mr *MockOverlayStoreMockRecorder) RemoveOverlay(ctx, entry any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveOverlay", reflect.TypeOf((*MockOverlayStore)(nil).RemoveOverlay), ctx, entry)
}
