// Code generated by interfacer; DO NOT EDIT

package gogh

import (
)

// Env is an interface generated for "github.com/kyoh86/gogh/env.Access".
type Env interface {
	GithubHost() string
	GithubUser() string
	Hooks() []string
	Roots() []string
}
