// Code generated by MockGen. DO NOT EDIT.
// Source: overlay/service.go
//
// Generated by this command:
//
//	mockgen -source overlay/service.go -destination overlay_mock/gen_service_mock.go -package overlay_mock
//

// Package overlay_mock is a generated GoMock package.
package overlay_mock

import (
	context "context"
	io "io"
	iter "iter"
	reflect "reflect"

	overlay "github.com/kyoh86/gogh/v4/core/overlay"
	gomock "go.uber.org/mock/gomock"
)

// MockOverlayService is a mock of OverlayService interface.
type MockOverlayService struct {
	ctrl     *gomock.Controller
	recorder *MockOverlayServiceMockRecorder
	isgomock struct{}
}

// MockOverlayServiceMockRecorder is the mock recorder for MockOverlayService.
type MockOverlayServiceMockRecorder struct {
	mock *MockOverlayService
}

// NewMockOverlayService creates a new mock instance.
func NewMockOverlayService(ctrl *gomock.Controller) *MockOverlayService {
	mock := &MockOverlayService{ctrl: ctrl}
	mock.recorder = &MockOverlayServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOverlayService) EXPECT() *MockOverlayServiceMockRecorder {
	return m.recorder
}

// Add mocks base method.
func (m *MockOverlayService) Add(ctx context.Context, entry overlay.Entry) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Add", ctx, entry)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Add indicates an expected call of Add.
func (mr *MockOverlayServiceMockRecorder) Add(ctx, entry any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Add", reflect.TypeOf((*MockOverlayService)(nil).Add), ctx, entry)
}

// Get mocks base method.
func (m *MockOverlayService) Get(ctx context.Context, idlike string) (overlay.Overlay, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, idlike)
	ret0, _ := ret[0].(overlay.Overlay)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockOverlayServiceMockRecorder) Get(ctx, idlike any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockOverlayService)(nil).Get), ctx, idlike)
}

// HasChanges mocks base method.
func (m *MockOverlayService) HasChanges() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HasChanges")
	ret0, _ := ret[0].(bool)
	return ret0
}

// HasChanges indicates an expected call of HasChanges.
func (mr *MockOverlayServiceMockRecorder) HasChanges() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasChanges", reflect.TypeOf((*MockOverlayService)(nil).HasChanges))
}

// List mocks base method.
func (m *MockOverlayService) List() iter.Seq2[overlay.Overlay, error] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List")
	ret0, _ := ret[0].(iter.Seq2[overlay.Overlay, error])
	return ret0
}

// List indicates an expected call of List.
func (mr *MockOverlayServiceMockRecorder) List() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockOverlayService)(nil).List))
}

// Load mocks base method.
func (m *MockOverlayService) Load(arg0 iter.Seq2[overlay.Overlay, error]) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Load", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Load indicates an expected call of Load.
func (mr *MockOverlayServiceMockRecorder) Load(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Load", reflect.TypeOf((*MockOverlayService)(nil).Load), arg0)
}

// MarkSaved mocks base method.
func (m *MockOverlayService) MarkSaved() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "MarkSaved")
}

// MarkSaved indicates an expected call of MarkSaved.
func (mr *MockOverlayServiceMockRecorder) MarkSaved() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkSaved", reflect.TypeOf((*MockOverlayService)(nil).MarkSaved))
}

// Open mocks base method.
func (m *MockOverlayService) Open(ctx context.Context, idlike string) (io.ReadCloser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Open", ctx, idlike)
	ret0, _ := ret[0].(io.ReadCloser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Open indicates an expected call of Open.
func (mr *MockOverlayServiceMockRecorder) Open(ctx, idlike any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Open", reflect.TypeOf((*MockOverlayService)(nil).Open), ctx, idlike)
}

// Remove mocks base method.
func (m *MockOverlayService) Remove(ctx context.Context, idlike string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Remove", ctx, idlike)
	ret0, _ := ret[0].(error)
	return ret0
}

// Remove indicates an expected call of Remove.
func (mr *MockOverlayServiceMockRecorder) Remove(ctx, idlike any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Remove", reflect.TypeOf((*MockOverlayService)(nil).Remove), ctx, idlike)
}

// Update mocks base method.
func (m *MockOverlayService) Update(ctx context.Context, idlike string, entry overlay.Entry) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, idlike, entry)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockOverlayServiceMockRecorder) Update(ctx, idlike, entry any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockOverlayService)(nil).Update), ctx, idlike, entry)
}
