// Code generated by ../../../../go/pkg/mod/github.com/kyoh86/appenv@v0.1.0/generate.go DO NOT EDIT.

package config

import (
	yaml "github.com/goccy/go-yaml"
	"io"
)

type YAML struct {
	GithubHost *GithubHost `yaml:"githubHost,omitempty"`
	GithubUser *GithubUser `yaml:"githubUser,omitempty"`
	Roots      *Roots      `yaml:"roots,omitempty"`
	Hooks      *Hooks      `yaml:"hooks,omitempty"`
}

func saveYAML(w io.Writer, yml *YAML) error {
	return yaml.NewEncoder(w).Encode(yml)
}

var EmptyYAMLReader io.Reader = nil

func loadYAML(r io.Reader) (yml YAML, err error) {
	if r == EmptyYAMLReader {
		return
	}
	err = yaml.NewDecoder(r).Decode(&yml)
	return
}
