// Code generated by MockGen. DO NOT EDIT.
// Source: hook/store.go
//
// Generated by this command:
//
//	mockgen -source hook/store.go -destination hook_mock/gen_store_mock.go -package hook_mock
//

// Package hook_mock is a generated GoMock package.
package hook_mock

import (
	context "context"
	reflect "reflect"

	hook "github.com/kyoh86/gogh/v4/core/hook"
	gomock "go.uber.org/mock/gomock"
)

// MockHookStore is a mock of HookStore interface.
type MockHookStore struct {
	ctrl     *gomock.Controller
	recorder *MockHookStoreMockRecorder
	isgomock struct{}
}

// MockHookStoreMockRecorder is the mock recorder for MockHookStore.
type MockHookStoreMockRecorder struct {
	mock *MockHookStore
}

// NewMockHookStore creates a new mock instance.
func NewMockHookStore(ctrl *gomock.Controller) *MockHookStore {
	mock := &MockHookStore{ctrl: ctrl}
	mock.recorder = &MockHookStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHookStore) EXPECT() *MockHookStoreMockRecorder {
	return m.recorder
}

// Load mocks base method.
func (m *MockHookStore) Load(ctx context.Context, initial func() hook.HookService) (hook.HookService, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Load", ctx, initial)
	ret0, _ := ret[0].(hook.HookService)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Load indicates an expected call of Load.
func (mr *MockHookStoreMockRecorder) Load(ctx, initial any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Load", reflect.TypeOf((*MockHookStore)(nil).Load), ctx, initial)
}

// Save mocks base method.
func (m *MockHookStore) Save(ctx context.Context, v hook.HookService, force bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, v, force)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockHookStoreMockRecorder) Save(ctx, v, force any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockHookStore)(nil).Save), ctx, v, force)
}

// Source mocks base method.
func (m *MockHookStore) Source() (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Source")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Source indicates an expected call of Source.
func (mr *MockHookStoreMockRecorder) Source() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Source", reflect.TypeOf((*MockHookStore)(nil).Source))
}
