// Code generated by main.go DO NOT EDIT.

package env

import (
	yaml "gopkg.in/yaml.v3"
	"io"
)

type File struct {
	Roots      *Roots      `yaml:"roots,omitempty"`
	GithubHost *GithubHost `yaml:"githubHost,omitempty"`
}

func SaveFile(w io.Writer, file *File) error {
	return yaml.NewEncoder(w).Encode(file)
}

func LoadFile(r io.Reader) (file File, err error) {
	err = yaml.NewDecoder(r).Decode(&file)
	return
}
