// Code generated by main.go DO NOT EDIT.

package env

import (
	keyring "github.com/zalando/go-keyring"
	"log"
)

type Keyring struct {
	GithubToken *GithubToken
}

func LoadKeyring(serviceName string) (key Keyring, err error) {
	{
		v, err := keyring.Get(serviceName, "github-token")
		if err == nil {
			var value GithubToken
			if err = value.UnmarshalText([]byte(v)); err != nil {
				return key, err
			}
			key.GithubToken = &value
		} else {
			log.Printf("info: there's no secret in github-token@%s (%v)", serviceName, err)
		}
	}
	return
}

func SaveKeyring(serviceName string, key Keyring) (err error) {
	{
		buf, err := key.GithubToken.MarshalText()
		if err != nil {
			return err
		}
		if err := keyring.Set(serviceName, "github-token", string(buf)); err != nil {
			return err
		}
	}
	return nil
}
