// Code generated by main.go DO NOT EDIT.

package env

func Merge(file File, keyring Keyring, envar Envar) (merged Merged) {
	merged.roots = new(Roots).Default().([]string)
	if file.Roots != nil {
		merged.roots = file.Roots.Value().([]string)
	}
	if envar.Roots != nil {
		merged.roots = envar.Roots.Value().([]string)
	}

	merged.githubHost = new(GithubHost).Default().(string)
	if file.GithubHost != nil {
		merged.githubHost = file.GithubHost.Value().(string)
	}
	if envar.GithubHost != nil {
		merged.githubHost = envar.GithubHost.Value().(string)
	}

	merged.githubToken = new(GithubToken).Default().(string)
	if keyring.GithubToken != nil {
		merged.githubToken = keyring.GithubToken.Value().(string)
	}
	if envar.GithubToken != nil {
		merged.githubToken = envar.GithubToken.Value().(string)
	}

	return
}

type Merged struct {
	roots       []string
	githubHost  string
	githubToken string
}

func (m *Merged) Roots() []string {
	return m.roots
}

func (m *Merged) GithubHost() string {
	return m.githubHost
}

func (m *Merged) GithubToken() string {
	return m.githubToken
}
