// Code generated by main.go DO NOT EDIT.

package env

import (
	yaml "gopkg.in/yaml.v3"
	"io"
)

type YAML struct {
	Roots      *Roots      `yaml:"roots,omitempty"`
	GithubHost *GithubHost `yaml:"githubHost,omitempty"`
}

func saveYAML(w io.Writer, yml *YAML) error {
	return yaml.NewEncoder(w).Encode(yml)
}

func loadYAML(r io.Reader) (yml YAML, err error) {
	err = yaml.NewDecoder(r).Decode(&yml)
	return
}
