name: Deploy

on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v1
        with:
          go-version: 1.13.x
      - uses: actions/checkout@v1
      - name: get dependencies
        run: go get -v -t -d ./...
      - name: test race
        run: go test -v -race ./...
      - uses: goreleaser/goreleaser-action@v1
        with:
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GORELEASER_GITHUB_TOKEN }}
