# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Review
on: [pull_request]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: reviewdog/action-golangci-lint@v2
        with:
          level: info
          github_token: ${{ secrets.GITHUB_TOKEN }}
